"""fresh_init

Revision ID: 272644a8c576
Revises: 
Create Date: 2026-02-22 20:21:12.824879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272644a8c576'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('circuit_id', sa.String(length=100), nullable=False),
    sa.Column('circuit_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('circuit_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.String(length=100), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('driver_code', sa.String(length=10), nullable=True),
    sa.Column('driver_forename', sa.String(length=100), nullable=True),
    sa.Column('driver_surname', sa.String(length=100), nullable=True),
    sa.Column('driver_full_name', sa.String(length=200), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_table('races',
    sa.Column('race_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=False),
    sa.Column('circuit_id', sa.String(length=100), nullable=False),
    sa.Column('circuit_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.circuit_id'], ),
    sa.PrimaryKeyConstraint('race_id')
    )
    op.create_table('team_standings',
    sa.Column('standing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('standing_id')
    )
    op.create_table('driver_standings',
    sa.Column('standing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('standing_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('predicted_winner_id', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_top_3', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['predicted_winner_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('race_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.String(length=100), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(length=10), nullable=True),
    sa.Column('points', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('laps_completed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_table('weather_data',
    sa.Column('weather_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('rainfall', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conditions', sa.String(length=100), nullable=True),
    sa.Column('forecast_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('weather_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    op.drop_table('race_results')
    op.drop_table('predictions')
    op.drop_table('driver_standings')
    op.drop_table('team_standings')
    op.drop_table('races')
    op.drop_table('drivers')
    op.drop_table('teams')
    op.drop_table('circuits')
    # ### end Alembic commands ###
