"""add timestamps to all tables

Revision ID: 960416746ae2
Revises: e13b0fb49683
Create Date: 2026-02-22 17:37:44.630258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960416746ae2'
down_revision: Union[str, Sequence[str], None] = 'e13b0fb49683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('race_results_race_id_driver_id_key'), 'race_results', type_='unique')
    op.drop_constraint(op.f('races_year_round_key'), 'races', type_='unique')
    op.create_foreign_key(None, 'races', 'circuits', ['circuit_id'], ['circuit_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.create_unique_constraint(op.f('races_year_round_key'), 'races', ['year', 'round'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('race_results_race_id_driver_id_key'), 'race_results', ['race_id', 'driver_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
