"""Initial migration - all tables

Revision ID: a93200edc9a1
Revises: 
Create Date: 2026-02-15 17:12:11.031652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93200edc9a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('driver_standings_year_driver_id_key'), 'driver_standings', type_='unique')
    op.drop_index(op.f('idx_driver_standings_driver_id'), table_name='driver_standings')
    op.drop_index(op.f('idx_driver_standings_year'), table_name='driver_standings')
    op.drop_index(op.f('idx_drivers_full_name'), table_name='drivers')
    op.alter_column('predictions', 'predicted_top_3',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_predictions_race_id'), table_name='predictions')
    op.drop_index(op.f('idx_race_results_driver_id'), table_name='race_results')
    op.drop_index(op.f('idx_race_results_race_id'), table_name='race_results')
    op.drop_index(op.f('idx_race_results_team_id'), table_name='race_results')
    op.drop_constraint(op.f('race_results_race_id_driver_id_key'), 'race_results', type_='unique')
    op.drop_index(op.f('idx_races_date'), table_name='races')
    op.drop_index(op.f('idx_races_year'), table_name='races')
    op.drop_constraint(op.f('races_year_round_key'), 'races', type_='unique')
    op.drop_index(op.f('idx_team_standings_team_id'), table_name='team_standings')
    op.drop_index(op.f('idx_team_standings_year'), table_name='team_standings')
    op.drop_constraint(op.f('team_standings_year_team_id_key'), 'team_standings', type_='unique')
    op.drop_index(op.f('idx_weather_data_race_id'), table_name='weather_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_weather_data_race_id'), 'weather_data', ['race_id'], unique=False)
    op.create_unique_constraint(op.f('team_standings_year_team_id_key'), 'team_standings', ['year', 'team_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_team_standings_year'), 'team_standings', ['year'], unique=False)
    op.create_index(op.f('idx_team_standings_team_id'), 'team_standings', ['team_id'], unique=False)
    op.create_unique_constraint(op.f('races_year_round_key'), 'races', ['year', 'round'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_races_year'), 'races', ['year'], unique=False)
    op.create_index(op.f('idx_races_date'), 'races', ['date'], unique=False)
    op.create_unique_constraint(op.f('race_results_race_id_driver_id_key'), 'race_results', ['race_id', 'driver_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_race_results_team_id'), 'race_results', ['team_id'], unique=False)
    op.create_index(op.f('idx_race_results_race_id'), 'race_results', ['race_id'], unique=False)
    op.create_index(op.f('idx_race_results_driver_id'), 'race_results', ['driver_id'], unique=False)
    op.create_index(op.f('idx_predictions_race_id'), 'predictions', ['race_id'], unique=False)
    op.alter_column('predictions', 'predicted_top_3',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_drivers_full_name'), 'drivers', ['driver_full_name'], unique=False)
    op.create_index(op.f('idx_driver_standings_year'), 'driver_standings', ['year'], unique=False)
    op.create_index(op.f('idx_driver_standings_driver_id'), 'driver_standings', ['driver_id'], unique=False)
    op.create_unique_constraint(op.f('driver_standings_year_driver_id_key'), 'driver_standings', ['year', 'driver_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
